# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouyinOfSun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'Kingfisher', '5.3.1'
pod 'SnapKit'
pod 'HandyJSON', '5.0.0-beta.1'
pod 'libwebp'
pod 'PLPlayerKit', :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'

  # Pods for DouyinOfSun

end

